name: cloud_messaging
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_signin_button: ^2.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
